void lcdinit(int io_register, int pin_register, int device);
void write_pins(int value);
void write_pins_append(int value);
void write_pins_remove(int value);
void reset_all();
void write_4_bits(int bits, int char_mode);
void set_enable(int on);
void set_rs(int on);
void pulse_enable();
void write_char(char chr);
void write_string(char *str);
void clear_screen();
void cursor_off();
void cursor_on();
void screen_off();
void screen_on();
void cursor_blink_off();
void cursor_blink_on();
void write_display_mode_change(int change, int on);
void cursor_right(int num);
void cursor_left(int num);
